### ISSUE TITLE
Are you able to share the complete codes?

### ISSUE THREAD

**Issue by trex1998** [ashishsalunkhe/Aspect-based-Financial-Sentiment-Analysis#1]
Hi, Ashish Salunkhe
I am a student who is interested in NLP and currently I am studying Aspect based sentiment analysis myself.
I have read your paper "Aspect Based Sentiment Analysis on Financial Data using Transferred Learning Approach using Pre-Trained BERT and Regressor Model", and think it is really applicable and great job, especially in financial domain.. 
I tried to replicate your work but face some problems, so could you share the codes for this project if possible?
I would be really grateful. Thank you.

**Comment by ashishsalunkhe** [comment]
Hello,
I've added the Jupyter Notebook File to the Github repository itself.

Regards,
Ashish Salunkhe
ashishsalunkhe.github.io
Pune, India
