### ISSUE TITLE
How to convert the json data into csv

### ISSUE THREAD

**Issue by ShivanshuPurohit** [ashishsalunkhe/Aspect-based-Financial-Sentiment-Analysis#2]
If I read the json file into a df, it looks like this
![image](https://user-images.githubusercontent.com/42869065/141686177-4595db20-1504-485a-b7be-d5ab69d4b6ae.png)
How do I convert it to csv like in your notebook?

**Comment by cheese7858** [comment]
Hi there, I'm having the same issue here, did you manage to convert it to csv?
Kind regards,
